project:
  type: website

website:
  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    title: " "
    tools:
      - icon: house-fill
        href: https://isss608-ohjiawen.netlify.app/
      - icon: github
        href: https://github.com/jiawenoh/ISSS608-VAA
      - icon: linkedin
        href: https://www.linkedin.com/in/jia-wen-oh/
        
    background: light
    reader-mode: true
    collapse-level: 1
    contents:
      - section: "About"
        contents: 
          - text: "Home"
            href: "index.qmd"
         
      - section: "Hands-on Exercise"
        contents:
          - text: "Exercise 1A: Geospatial Data Wrangling"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Exercise 1B: Choropleth Mapping"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"

      - section: "In-class Exercise"
        contents:
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"

            
      - section: "Take Home Exercise"
        contents:
          - text: "Take Home Exercise 1"
            href: "Take-Home_Ex/Take_Home_Ex01/Take-Home_Ex01.html"
          - text: "Take Home Exercise 2"
            href: "Take-Home_Ex/Take_Home_Ex02/Take-Home_Ex02.html"


format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    toc: true
    css: styles.css         
    code-fold: false
    code-summary: "Show the code"
    
editor: visual
